import loadable from 'react-loadable-visibility/loadable-components';

// Do not modify anything within the `<auto-generated-imports />` comments.
// The content within those comments is automatically generated by
// the `/scripts/generate-component-factory.js` script.

// <auto-generated-imports>


// </auto-generated-imports>


export default function componentFactory(componentName: string) {
  return components.get(componentName);
}
