name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: export
      run: npm run export
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        UNIFORM_API_URL: ${{ secrets.UNIFORM_API_URL }}
        UNIFORM_DATA_URL: ${{ secrets.UNIFORM_DATA_URL }}
        UNIFORM_API_KEY: ${{ secrets.UNIFORM_API_KEY }}
        GA_UA_ID: ${{ secrets.GA_UA_ID }}
        MAPS_APIKEY: ${{ secrets.MAPS_APIKEY }}
        CLOUDINARY_ACCOUNT: ${{ secrets.CLOUDINARY_ACCOUNT }}
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_COAST_057F9361E }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: 'upload'
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        app_location: '/out' # App source code path
        #app_build_command: npm run export
        api_location: 'api' # Api source code path - optional
        #app_artifact_location: '/out' # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_COAST_057F9361E }}
        action: 'close'
